description: Taux de la contribution sociale généralisée (CSG) sur sur les produits de placement
values:
  2026-01-01:
    value: 0.092
metadata:
  short_label: Produits de placement
  last_value_still_valid_on: "2026-01-01"
  label_en: smaller CSG on financial income
  ipp_csv_id: tx_csg_rk_plac
  unit: /1
  reference:
    2019-01-01:
      - title: Code de la sécurité sociale - art. L136-6
        href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033812508/2019-01-01/
      - title: Code de la sécurité sociale - art. L136-8
        href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042683546/2019-01-01/
      - title: Loi 2018-1203 du 22/12/2018 - art. 26 (modifie l'art. L136-8 du CSS)
        href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000037847610
  official_journal_date:
    2019-01-01: "2018-12-23"
