description: Montant de base de l'aide exceptionnelle de solidarité covid-19
values:
  2020-05-01:
    value: 150
  2020-06-01:
    value: 0
  2020-10-01:
    value: 150
  2020-11-01:
    value: null
metadata:
  short_label: Montant de base
  label_en: Exceptional benefit - covid-19 crisis
  ipp_csv_id: aide_exceptionnelle_covid_base
  unit: currency
  reference:
    2020-05-01:
    - title: Décret 2020-519 du 05/05/2020
      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000041849630/
    - title: Décret 2020-769 du 24/06/2020
      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042032514
    2020-10-01:
      title: Décret n°2020-1453 du 27/11/2020
      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042574431
  official_journal_date:
    2020-05-01: 2020-05-06; 2020-06-25
    2020-10-01: "2020-11-28"
  notes:
    2020-06-01:
    - title: L'aide ne peut être versée qu'une seule fois et n'est donc plus en vigueur le mois suivant son instauration
    2020-11-01:
    - title: L'aide ne peut être versée qu'une seule fois et n'est donc plus en vigueur le mois suivant son instauration
documentation: |-
  Notes :
  Montant versable aux bénéficiaires d'une des allocations suivantes, au titre du mois courant ou du mois précédent :  Revenu de solidarité active (RSA), Revenu de solidarité (RSO), Allocation de solidarité spécifique (ASS), Prime forfaitaire mensuelle d'activité, Allocation équivalent retraite (AER). Il n'y a pas de majoration pour les couples.
