description: Abattement forfaitaire de base sur les revenus du conjoint (revenus d'activité, pensions, rentes viagères à titre gratuit) pour le calcul de l'allocation aux adultes handicapés (AAH)
values:
  2022-01-01:
    value: 5000
metadata:
  last_value_still_valid_on: "2025-04-01"
  short_label: Abattement forfaitaire de base
  label_en: Adult disability allowance (AAH)
  ipp_csv_id: abattement_aah_conjoint_forfaitaire_base
  unit: currency
  reference:
    2022-01-01:
      title: Décret n° 2022-42 du 19/01/2022
      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000045038484#:~:text=Il%20fixe%20notamment%20le%20montant,au%20sens%20des%20prestations%20familiales.
  official_journal_date:
    2022-01-01: "2022-01-20"
documentation: Article D821-8-1 est Abrogé par le Décret n° 2023-360 du 11 mai 2023, cependant la page https://www.monparcourshandicap.gouv.fr/aides/lallocation-aux-adultes-handicapes-aah mentionne toujours cette abattement.
