description: Âge maximum (fin de dernier contrat) pour que la dégressivité s'applique
unit: year
metadata:
  reference:
    2025-04-01:
      title: Article 17bis du règlement général annexé à la convention du 15 novembre 2024 relative à l'assurance chômage agréée par arrêté du 19 décembre 2024
      href: https://www.unedic.org/ged/documents/regulatory_texts/pdf/TXT-RG-Reglement_general_annexe_a_la_convention.pdf
    2019-11-01:
      title: Article 17bis du règlement annexé au décret n° 2019-797 du 26 juillet 2019 relatif au régime d'assurance chômage
      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000038869230

values:
  2025-04-01:
    value: 55
  2019-11-01:
    value: 57
