#! /usr/bin/env bash

python openfisca_france/scripts/yaml_round_trip.py $@

if ! git diff-index --name-only --exit-code HEAD -- $@
then
    echo "This or those files are not appropriately formatted."
    echo "Check CircleCI artfifacts to see the differences generated by openfisca_france/scripts/yaml_round_trip.py."

    # Outputs to STDERR
    (>&2 git --no-pager diff HEAD -- $@)
    exit 3
fi
