#! /usr/bin/env bash

python openfisca_france/scripts/yaml_round_trip.py $@

if [ $? -ne 0 ]
then
    echo "python openfisca_france/scripts/yaml_round_trip.py failed."

    exit 1
fi

git --no-pager diff --exit-code $@ > /dev/null

if [ $? -ne 0 ]
then
    git diff-index --name-only --patience --exit-code HEAD $@

    echo "This or those files are not appropriately formatted."
    echo "Check CircleCI artfifacts to see the differences generated by openfisca_france/scripts/yaml_round_trip.py."

    # Outputs to STDERR
    (>&2 git --no-pager diff HEAD -- $@)
    exit 2
fi
