description: Base de la Majoration du montant de l'Allocation de salaire unique (ASU, 1941-1977)
values:
  1976-07-01:
    value: 388.2
  1978-01-01:
    value: null
metadata:
  short_label: Base
  label_en: "Single earner allowance (ASU): Monthly amount"
  ipp_csv_id: majo_base
  unit: currency
  reference:
    1976-07-01:
    - title: Loi 72-8 du 03/01/1972
    - title: Décret 72-530 du 29/06/1972 (S.U.)
    - title: Décret 76-767 du 16/08/1976 ("Majoration")
    1978-01-01:
      title: Loi 77-765 du 12/07/1977
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000886344
  official_journal_date:
    1976-07-01: 1972-01-05; 1972-06-30; 1976-08-17
    1978-01-01: "1977-07-13"
  notes:
    1976-07-01:
    - title: Réservé aux ménages avec un seul revenu, sauf si l'autre conjoint a un revenu ne dépassant pas la moitié de la base de calcul des AF soit 347,25
documentation: |-
  Notes :
  L'Allocation de salaire unique est instituée en 1941 par la loi du 29 mars 1941 parue au JO du 11 avril 1941 page 1555
  l'ASU ne peut se cumuler avec l'allocation de la mère au foyer.
  L'ASU est versée tant que l'âge du plus jeune enfant est inférieur à
  La base est identique à celle des allocations familiales (au salaire moyen départemental) jusqu'en 1954, puis une base inférieure à celle des AF est créée en 1955(égale à 180 FRF en 1959 pour la région parisienne, 162FRF pour la dernière zone contre 210FRF et 189FRF respectivement pour les AF)
