# When using openfisca for a large population, having too many variables in cache make openfisca performances drop.
# The following variables are intermediate results and do not need to be cached in those usecases.

cache_blacklist = set([
    'agepi_temps_travail_semaine',
    'aide_financement_permis_apprenti_eligibilite',
    'aide_permis_demandeur_emploi_eligibilite_financiere',
    'aide_permis_demandeur_emploi_eligibilite_individu',
    'aide_logement_loyer_retenu',
    'aide_logement_charges',
    'aide_logement_R0',
    'aide_logement_taux_famille',
    'aide_logement_taux_loyer',
    'aide_logement_participation_personnelle',
    'aide_logement_montant_brut_avant_degressivite',
    'aides_logement_primo_accedant',
    'aides_logement_primo_accedant_k',
    'aides_logement_nb_part',
    'aides_logement_primo_accedant_plafond_mensualite',
    'aides_logement_primo_accedant_ressources',
    'cheque_energie',
    'garantie_jeunes_max',
    'garantie_jeunes_neet',
    'garantie_jeunes_eligibilite_age',
    'locapass_eligibilite_etudiant',
    'locapass_eligibilite_etudiant_contrat',
    'locapass_eligibilite_individu',
    'locapass_eligibilite_jeunes',
    'locapass_eligibilite_logement',
    'locapass_eligibilite_salarie',
    'montant_cheque_energie',
    'ppa_forfait_logement',
    'ppa_plancher_revenu_activite_etudiant',
    'unites_consommation_cheque_energie',
    ])
