description: Taux de la contribution sociale généralisée (CSG) déductible sur les produits de placement
values:
  1990-01-01:
    value: null
  2007-01-01:
    value: 0.058
  2012-01-01:
    value: 0.051
  2018-01-01:
    value: 0.068
metadata:
  short_label: Produits de placement
  last_value_still_valid_on: "2018-01-01"
  label_en: CSG on financial income
  ipp_csv_id: tx_csg_ded_rk_plac
  unit: /1
  reference:
    1990-01-01:
      title: Loi 90-1168 du 29/12/1990, art. 132 et 134 (LF pour 1991)
    2007-01-01:
      title: Loi 2006-1640 du 21/12/2006, art. 20 (LFSS pour 2007)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006759270&cidTexte=JORFTEXT000000817095
    2012-01-01:
      title: Loi 2012-1509 du 29/12/2012, art. 9 (LF pour 2013)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000026872653&cidTexte=JORFTEXT000026856853
    2018-01-01:
    - title: Loi 2017-1836 du 30/12/2017 - art. 8 (V) (modifie l'art. L136-8 du CSS)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000036358456&cidTexte=JORFTEXT000036339090
    - title: Loi 2017-1837 du 30/12/2017 - art. 67 (modifie l'art. 154 quinquies)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000036377512&cidTexte=JORFTEXT000036339197
    - title: LOI 2018-1203 du 22/12/2018, art. 26 (modifie l'art. L136-8 du CSS)
  official_journal_date:
    1990-01-01: "1990-12-30"
    2007-01-01: "2006-12-22"
    2012-01-01: "2012-12-30"
    2018-01-01: "2017-12-31"
  notes:
    2012-01-01:
    - title: "Le recours au prélèvement forfaitaire libératoire est limité à partir de 2013 à moins de 2000 € d'intérêts annuels pour les revenus de placement: ceux-ci ne bénéficient pasde la CSG déductible, au même titre que les bons détenus anonymement. Le PFL est également maintenu pour les bons ou contrats de capitalisation et placements qui ne bénéficient pas de la CSG déductible."
documentation: En ce qui concerne l'assiette CSG, l'abattement sur l'impôt sur le revenu, appliqué jusqu'à sa suppression en 1997, ne concerne pas les revenus mobiliers soumis à prélèvement libératoire ou exonérés d'impôt sur le revenu ainsi que les plus-values mobilières.
