#! /usr/bin/env python
# -*- coding: utf-8 -*-

from openfisca_france.scripts.calculateur_impots.input_scenario_builder.utils import *



fixed_wage_amount = 50000
tested_income_amount = 20000
tested_reduction_amount = 500

scenario_by_variable_2014 = {
    'abat_65_or_invalid': define_single_worker_scenario(2014, {'salaire_imposable': 20000},  caseP = 1, date_naissance = 2014 - 80),
    'caseF': define_family_scenario(2014, caseF = 1),
    'caseG': define_single_worker_scenario(2014, {'salaire_imposable': 50000}, caseG = 1, statut_marital = u'veuf', date_naissance = 2014 - 80),
    'caseL': define_single_worker_scenario(2014, {'salaire_imposable': 50000}, caseL = 1),
    'caseP': define_family_scenario(2014, caseP = 1),
    'caseS': define_family_scenario(2014, caseS = 1, date_naissance1 = 2014 - 80),
    'caseT': define_single_worker_scenario(2014,  {'salaire_imposable': fixed_wage_amount}, nb_enfants = 1, nbF = 1, caseT = 1),
    'caseW': define_single_worker_scenario(2014, {'salaire_imposable': 50000}, caseW = 1, date_naissance = 2014 - 80),
    'charges_deduc_non_plafonnees_acc75a': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f6ev': 2, 'f6eu': 1000}),
    'charges_deduc_non_plafonnees_deddiv': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f6dd': tested_reduction_amount}),
    #'charges_deduc_non_plafonnees_eparet': TODO
    'charges_deduc_non_plafonnees_reparations': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f6cb': 25000, 'f6hj': 1000 , 'f6hk': 1000, 'f6hl': 1000, 'f6hm': 1000, 'f6hn': 1000}),
    'charges_deduc_non_plafonnees_pens_alim': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f6gi': tested_reduction_amount, 'f6gj': tested_reduction_amount, 'f6el': tested_reduction_amount, 'f6em': tested_reduction_amount, 'f6gp': tested_reduction_amount, 'f6gu': tested_reduction_amount}),
    'credit_assloy': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f4ba': tested_income_amount, 'f4bf': tested_reduction_amount}),
    'credit_garext': define_family_scenario(2014, value_by_variable = {'f7ga': 3000, 'f7ge': 2000}, nb_enfants = 2, nbF = 1, nbH = 1),
    'credit_inthab': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7vt': tested_reduction_amount, 'f7vx': tested_reduction_amount * 2, 'f7vz': tested_reduction_amount * 3}),
    'credit_preetu': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7uk': 1000, 'f7vo': 2, 'f7td': 3000}, date_naissance = 2014 - 25),
    'credit_saldom': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7db': tested_income_amount, 'f7dq': 1, 'f7dg': 1}),
    'decote': define_family_scenario(2014, income_amount1 = 25000, income_amount2 = 20000),
    'f4be': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f4be': 15000}), # régime micro-foncier
    'maj_nbp': define_family_scenario(2014, nbF = 1, nbG = 1, nbH = 1, nbI = 1, nbR = 1, nbJ = 1),
    'nbG': define_family_scenario(2014, nbG = 1),  
    'nbI': define_family_scenario(2014, nbF = 2, nbI = 1, nbH = 1),
    'nbR': define_family_scenario(2014, nbR = 1),
    'plaf_qf_caseL': define_single_worker_scenario(2014, {'salaire_imposable': 150000}, caseL = 1),
    'plaf_qf_casePF_nbGI': define_family_scenario(2014, income_amount1 = 150000, income_amount2 = 100000, caseP = 1, caseF = 1, nbF = 2, nbG = 1, nbH = 1, nbI = 1),
    'plaf_qf_caseT': define_single_worker_scenario(2014,  {'salaire_imposable': 150000}, nb_enfants = 1, nbF = 1, caseT = 1),
    'plaf_qf_caseWG': define_single_worker_scenario(2014, {'salaire_imposable': 150000}, statut_marital = u'veuf', caseG = 1, caseW = 1),
    'plaf_qf_family': define_family_scenario(2014, income_amount1 = 150000, income_amount2 = 100000),
    'ppe': define_family_scenario(2014, income_amount1 = 15000, income_amount2 = 10000), 
    'reduc_adhcga': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7ff': tested_reduction_amount, 'f7fg': 2}),
    'reduc_autent': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7uy': tested_reduction_amount}),
    'reduc_credit_2042pro': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'arag_impg': fixed_wage_amount, 'f8tb': tested_reduction_amount, 'f8tc' : tested_reduction_amount, 'f8te' : tested_reduction_amount, 'f8tg' : tested_reduction_amount, 'f8ts' : tested_reduction_amount, 'f8tz' : tested_reduction_amount, 'f8wa' : tested_reduction_amount, 'f8wb' : tested_reduction_amount, 'f8wc' : tested_reduction_amount, 'f8wd' : tested_reduction_amount, 'f8we' : tested_reduction_amount, 'f8wt' : tested_reduction_amount, 'f8wr' : tested_reduction_amount, 'f8uz' : tested_reduction_amount, 'f8wu' : tested_reduction_amount, 'f8tl' : tested_reduction_amount, 'f8uw' : tested_reduction_amount}), 
    'reduc_duflot_rpinel': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7el': 200000, 'f7qc': 150000, 'f7qe': tested_reduction_amount, 'f7qh': tested_reduction_amount, 'f7qj': tested_reduction_amount, 'f7ql': tested_reduction_amount, 'f7ai': tested_reduction_amount, 'f7gh': tested_reduction_amount, 'f7fi': tested_reduction_amount}),
    'reduc_dfppce' : define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7uf': tested_reduction_amount, 'f7vc': tested_reduction_amount, 'f7xs': 1000, 'f7xt': 1000, 'f7xu': 1000, 'f7xv': 1000, 'f7xw': 1000}),
    'reduc_donapd' : define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7ud': 100, 'f7va': 100}),
    'reduc_ecpess': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount,'f7ea': 1, 'f7eb': 1, 'f7ec': 0, 'f7ef': 0, 'f7eg': 0, 'f7ed': 1}, nb_enfants = 3, nbF = 1, nbH = 2),
    'reduc_intagr': define_single_worker_scenario(2014,  {'salaire_imposable': fixed_wage_amount, 'f7um': tested_income_amount, 'f2tr': tested_income_amount}),
    'reduc_invlst1': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7uy': 5000}),
    'reduc_invlst2': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7uz': 5000}),
    'reduc_patnat': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7kb': tested_reduction_amount, 'f7kc': tested_reduction_amount, 'f7kd': tested_reduction_amount, 'f7ke': tested_reduction_amount}),
    'reduc_malraux': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7ny': tested_reduction_amount, 'f7nx': tested_reduction_amount, 'f7re': tested_reduction_amount, 'f7rf': tested_reduction_amount, 'f7sy': tested_reduction_amount, 'f7sx': tested_reduction_amount}),
    'reduc_saldom' : define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7df': tested_income_amount, 'f7dq': 0, 'f7dg': 0}),
    'reduc_saldom2': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7dd': tested_income_amount, 'f7dl': 1}),
    'reduc_spfscpi': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount, 'f7fq': tested_reduction_amount * 2, 'f7fm': tested_reduction_amount * 3}),
    'reduc_spfscpi2': define_single_worker_scenario(2014, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount}),
}

scenario_by_variable_2015 = {
    'abat_65_or_invalid': define_single_worker_scenario(2015, {'salaire_imposable': 20000},  caseP = 1, date_naissance = 2015 - 80),
    'caseF': define_family_scenario(2015, caseF = 1),
    'caseG': define_single_worker_scenario(2015, {'salaire_imposable': 50000}, caseG = 1, statut_marital = u'veuf', date_naissance = 2015 - 80),
    'caseL': define_single_worker_scenario(2015, {'salaire_imposable': 50000}, caseL = 1),
    'caseP': define_family_scenario(2015, caseP = 1),
    'caseS': define_family_scenario(2015, caseS = 1, date_naissance1 = 2015 - 80),
    'caseT': define_single_worker_scenario(2015,  {'salaire_imposable': fixed_wage_amount}, nb_enfants = 1, nbF = 1, caseT = 1),
    'caseW': define_single_worker_scenario(2015, {'salaire_imposable': 50000}, caseW = 1, date_naissance = 2015 - 80),
    'charges_deduc_non_plafonnees_acc75a': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f6ev': 2, 'f6eu': 1000}),
    'charges_deduc_non_plafonnees_deddiv': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f6dd': tested_reduction_amount}),
    #'charges_deduc_non_plafonnees_eparet': TODO
    'charges_deduc_non_plafonnees_reparations': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f6cb': 25000, 'f6hj': 1000 , 'f6hk': 1000, 'f6hl': 1000, 'f6hm': 1000, 'f6hn': 1000, 'f6ho': 1000}),
    'charges_deduc_non_plafonnees_pens_alim': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f6gi': tested_reduction_amount, 'f6gj': tested_reduction_amount, 'f6el': tested_reduction_amount, 'f6em': tested_reduction_amount, 'f6gp': tested_reduction_amount, 'f6gu': tested_reduction_amount}),
    'credit_assloy': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f4ba': tested_income_amount, 'f4bf': tested_reduction_amount}),
    'credit_garext': define_family_scenario(2015, value_by_variable = {'f7ga': 3000, 'f7ge': 2000}, nb_enfants = 2, nbF = 1, nbH = 1),
    'credit_inthab': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7vt': tested_reduction_amount, 'f7vx': tested_reduction_amount * 2, 'f7vz': tested_reduction_amount * 3}),
    'credit_preetu': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7uk': 1000, 'f7vo': 2, 'f7td': 3000}, date_naissance = 2015 - 25),
    'credit_saldom': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7db': tested_income_amount, 'f7dq': 1, 'f7dg': 1}),
    'decote': define_family_scenario(2015, income_amount1 = 25000, income_amount2 = 20000),
    'f4be': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f4be': 15000}), # régime micro-foncier
    'maj_nbp': define_family_scenario(2015, nbF = 1, nbG = 1, nbH = 1, nbI = 1, nbR = 1, nbJ = 1),
    'nbG': define_family_scenario(2015, nbG = 1),  
    'nbI': define_family_scenario(2015, nbF = 2, nbI = 1, nbH = 1),
    'nbR': define_family_scenario(2015, nbR = 1),
    'plaf_qf_caseL': define_single_worker_scenario(2015, {'salaire_imposable': 150000}, caseL = 1),
    'plaf_qf_casePF_nbGI': define_family_scenario(2015, income_amount1 = 150000, income_amount2 = 100000, caseP = 1, caseF = 1, nbF = 2, nbG = 1, nbH = 1, nbI = 1),
    'plaf_qf_caseT': define_single_worker_scenario(2015,  {'salaire_imposable': 150000}, nb_enfants = 1, nbF = 1, caseT = 1),
    'plaf_qf_caseWG': define_single_worker_scenario(2015, {'salaire_imposable': 150000}, statut_marital = u'veuf', caseG = 1, caseW = 1),
    'plaf_qf_family': define_family_scenario(2015, income_amount1 = 150000, income_amount2 = 100000),
    'ppe': define_family_scenario(2015, income_amount1 = 15000, income_amount2 = 10000), 
    'reduc_adhcga': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7ff': tested_reduction_amount, 'f7fg': 2}),
    'reduc_autent': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7uy': tested_reduction_amount}),
    'reduc_credit_2042pro': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'arag_impg': fixed_wage_amount, 'f8tb': tested_reduction_amount, 'f8tc' : tested_reduction_amount, 'f8te' : tested_reduction_amount, 'f8tg' : tested_reduction_amount, 'f8ts' : tested_reduction_amount, 'f8tz' : tested_reduction_amount, 'f8wa' : tested_reduction_amount, 'f8wb' : tested_reduction_amount, 'f8wc' : tested_reduction_amount, 'f8wd' : tested_reduction_amount, 'f8we' : tested_reduction_amount, 'f8wt' : tested_reduction_amount, 'f8wr' : tested_reduction_amount, 'f8uz' : tested_reduction_amount, 'f8wu' : tested_reduction_amount, 'f8tl' : tested_reduction_amount, 'f8uw' : tested_reduction_amount}), 
    'reduc_duflot_rpinel': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7el': 200000, 'f7qc': 150000, 'f7qe': tested_reduction_amount, 'f7qh': tested_reduction_amount, 'f7qj': tested_reduction_amount, 'f7ql': tested_reduction_amount, 'f7ai': tested_reduction_amount, 'f7gh': tested_reduction_amount, 'f7fi': tested_reduction_amount}),
    'reduc_dfppce' : define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7uf': tested_reduction_amount, 'f7vc': tested_reduction_amount, 'f7xs': 1000, 'f7xt': 1000, 'f7xu': 1000, 'f7xv': 1000, 'f7xw': 1000}),
    'reduc_donapd' : define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7ud': 100, 'f7va': 100}),
    'reduc_ecpess': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount,'f7ea': 1, 'f7eb': 1, 'f7ec': 0, 'f7ef': 0, 'f7eg': 0, 'f7ed': 1}, nb_enfants = 3, nbF = 1, nbH = 2),
    'reduc_intagr': define_single_worker_scenario(2015,  {'salaire_imposable': fixed_wage_amount, 'f7um': tested_income_amount, 'f2tr': tested_income_amount}),
    'reduc_invlst1': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7uy': 5000}),
    'reduc_invlst2': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7uz': 5000}),
    'reduc_patnat': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7kb': tested_reduction_amount, 'f7kc': tested_reduction_amount, 'f7kd': tested_reduction_amount, 'f7ke': tested_reduction_amount}),
    'reduc_malraux': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7ny': tested_reduction_amount, 'f7nx': tested_reduction_amount, 'f7re': tested_reduction_amount, 'f7rf': tested_reduction_amount, 'f7sy': tested_reduction_amount, 'f7sx': tested_reduction_amount}),
    'reduc_saldom' : define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7df': tested_income_amount, 'f7dq': 0, 'f7dg': 0}),
    'reduc_saldom2': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7dd': tested_income_amount, 'f7dl': 1}),
    'reduc_spfscpi': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount, 'f7fq': tested_reduction_amount * 2, 'f7fm': tested_reduction_amount * 3}),
    'reduc_spfscpi2': define_single_worker_scenario(2015, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount}),
}

scenario_by_variable_2016 = {
    'abat_65_or_invalid': define_single_worker_scenario(2016, {'salaire_imposable': 20000},  caseP = 1, date_naissance = 2016 - 80),
    'caseF': define_family_scenario(2016, caseF = 1),
    'caseG': define_single_worker_scenario(2016, {'salaire_imposable': 50000}, caseG = 1, statut_marital = u'veuf', date_naissance = 2016 - 80),
    'caseL': define_single_worker_scenario(2016, {'salaire_imposable': 50000}, caseL = 1),
    'caseP': define_family_scenario(2016, caseP = 1),
    'caseS': define_family_scenario(2016, caseS = 1, date_naissance1 = 2016 - 80),
    'caseT': define_single_worker_scenario(2016,  {'salaire_imposable': fixed_wage_amount}, nb_enfants = 1, nbF = 1, caseT = 1),
    'caseW': define_single_worker_scenario(2016, {'salaire_imposable': 50000}, caseW = 1, date_naissance = 2016 - 80),
    'charges_deduc_non_plafonnees_acc75a': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f6ev': 2, 'f6eu': 1000}),
    'charges_deduc_non_plafonnees_deddiv': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f6dd': tested_reduction_amount}),
    #'charges_deduc_non_plafonnees_eparet': TODO
    'charges_deduc_non_plafonnees_reparations': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f6cb': 25000, 'f6hj': 1000 , 'f6hk': 1000, 'f6hl': 1000, 'f6hm': 1000, 'f6hn': 1000, 'f6ho': 1000, 'f6hp': 1000}),
    'charges_deduc_non_plafonnees_pens_alim': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f6gi': tested_reduction_amount, 'f6gj': tested_reduction_amount, 'f6el': tested_reduction_amount, 'f6em': tested_reduction_amount, 'f6gp': tested_reduction_amount, 'f6gu': tested_reduction_amount}),
    'credit_assloy': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f4ba': tested_income_amount, 'f4bf': tested_reduction_amount}),
    'credit_garext': define_family_scenario(2016, value_by_variable = {'f7ga': 3000, 'f7ge': 2000}, nb_enfants = 2, nbF = 1, nbH = 1),
    'credit_inthab': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7vt': tested_reduction_amount, 'f7vx': tested_reduction_amount * 2, 'f7vz': tested_reduction_amount * 3}),
    'credit_preetu': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7uk': 1000, 'f7vo': 2, 'f7td': 3000}, date_naissance = 2016 - 25),
    'credit_saldom': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7db': tested_income_amount, 'f7dq': 1, 'f7dg': 1}),
    'decote': define_family_scenario(2016, income_amount1 = 25000, income_amount2 = 20000),
    'f4be': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f4be': 15000}), # régime micro-foncier
    'maj_nbp': define_family_scenario(2016, nbF = 1, nbG = 1, nbH = 1, nbI = 1, nbR = 1, nbJ = 1),
    'nbG': define_family_scenario(2016, nbG = 1),  
    'nbI': define_family_scenario(2016, nbF = 2, nbI = 1, nbH = 1),
    'nbR': define_family_scenario(2016, nbR = 1),
    'plaf_qf_caseL': define_single_worker_scenario(2016, {'salaire_imposable': 150000}, caseL = 1),
    'plaf_qf_casePF_nbGI': define_family_scenario(2016, income_amount1 = 150000, income_amount2 = 100000, caseP = 1, caseF = 1, nbF = 2, nbG = 1, nbH = 1, nbI = 1),
    'plaf_qf_caseT': define_single_worker_scenario(2016,  {'salaire_imposable': 150000}, nb_enfants = 1, nbF = 1, caseT = 1),
    'plaf_qf_caseWG': define_single_worker_scenario(2016, {'salaire_imposable': 150000}, statut_marital = u'veuf', caseG = 1, caseW = 1),
    'plaf_qf_family': define_family_scenario(2016, income_amount1 = 150000, income_amount2 = 100000),
    'ppe': define_family_scenario(2016, income_amount1 = 15000, income_amount2 = 10000), 
    'reduc_adhcga': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7ff': tested_reduction_amount, 'f7fg': 2}),
    'reduc_autent': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7uy': tested_reduction_amount}),
    'reduc_credit_2042pro': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'arag_impg': fixed_wage_amount, 'f8tb': tested_reduction_amount, 'f8tc' : tested_reduction_amount, 'f8te' : tested_reduction_amount, 'f8tg' : tested_reduction_amount, 'f8ts' : tested_reduction_amount, 'f8tz' : tested_reduction_amount, 'f8wa' : tested_reduction_amount, 'f8wb' : tested_reduction_amount, 'f8wc' : tested_reduction_amount, 'f8wd' : tested_reduction_amount, 'f8we' : tested_reduction_amount, 'f8wt' : tested_reduction_amount, 'f8wr' : tested_reduction_amount, 'f8uz' : tested_reduction_amount, 'f8wu' : tested_reduction_amount, 'f8tl' : tested_reduction_amount, 'f8uw' : tested_reduction_amount}), 
    'reduc_duflot_rpinel': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7el': 200000, 'f7qc': 150000, 'f7qe': tested_reduction_amount, 'f7qh': tested_reduction_amount, 'f7qj': tested_reduction_amount, 'f7ql': tested_reduction_amount, 'f7ai': tested_reduction_amount, 'f7gh': tested_reduction_amount, 'f7fi': tested_reduction_amount}),
    'reduc_dfppce' : define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7uf': tested_reduction_amount, 'f7vc': tested_reduction_amount, 'f7xs': 1000, 'f7xt': 1000, 'f7xu': 1000, 'f7xv': 1000, 'f7xw': 1000}),
    'reduc_donapd' : define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7ud': 100, 'f7va': 100}),
    'reduc_ecpess': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount,'f7ea': 1, 'f7eb': 1, 'f7ec': 0, 'f7ef': 0, 'f7eg': 0, 'f7ed': 1}, nb_enfants = 3, nbF = 1, nbH = 2),
    'reduc_intagr': define_single_worker_scenario(2016,  {'salaire_imposable': fixed_wage_amount, 'f7um': tested_income_amount, 'f2tr': tested_income_amount}),
    'reduc_invlst1': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7uy': 5000}),
    'reduc_invlst2': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7uz': 5000}),
    'reduc_patnat': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7kb': tested_reduction_amount, 'f7kc': tested_reduction_amount, 'f7kd': tested_reduction_amount, 'f7ke': tested_reduction_amount}),
    'reduc_malraux': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7ny': tested_reduction_amount, 'f7nx': tested_reduction_amount, 'f7re': tested_reduction_amount, 'f7rf': tested_reduction_amount, 'f7sy': tested_reduction_amount, 'f7sx': tested_reduction_amount}),
    'reduc_saldom' : define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7df': tested_income_amount, 'f7dq': 0, 'f7dg': 0}),
    'reduc_saldom2': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7dd': tested_income_amount, 'f7dl': 1}),
    'reduc_spfscpi': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount, 'f7fq': tested_reduction_amount * 2, 'f7fm': tested_reduction_amount * 3}),
    'reduc_spfscpi2': define_single_worker_scenario(2016, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount}),
}

scenario_by_variable_2017 = {
    'abat_65_or_invalid': define_single_worker_scenario(2017, {'salaire_imposable': 20000},  caseP = 1, date_naissance = 2017 - 80),
    'caseF': define_family_scenario(2017, caseF = 1),
    'caseG': define_single_worker_scenario(2017, {'salaire_imposable': 50000}, caseG = 1, statut_marital = u'veuf', date_naissance = 2017 - 80),
    'caseL': define_single_worker_scenario(2017, {'salaire_imposable': 50000}, caseL = 1),
    'caseP': define_family_scenario(2017, caseP = 1),
    'caseS': define_family_scenario(2017, caseS = 1, date_naissance1 = 2017 - 80),
    'caseT': define_single_worker_scenario(2017,  {'salaire_imposable': fixed_wage_amount}, nb_enfants = 1, nbF = 1, caseT = 1),
    'caseW': define_single_worker_scenario(2017, {'salaire_imposable': 50000}, caseW = 1, date_naissance = 2017 - 80),
    'charges_deduc_non_plafonnees_acc75a': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f6ev': 2, 'f6eu': 1000}),
    'charges_deduc_non_plafonnees_deddiv': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f6dd': tested_reduction_amount}),
    #'charges_deduc_non_plafonnees_eparet': TODO
    'charges_deduc_non_plafonnees_reparations': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f6cb': 25000, 'f6hj': 1000 , 'f6hk': 1000, 'f6hl': 1000, 'f6hm': 1000, 'f6hn': 1000, 'f6ho': 1000, 'f6hp': 1000, 'f6hq': 1000}),
    'charges_deduc_non_plafonnees_pens_alim': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f6gi': tested_reduction_amount, 'f6gj': tested_reduction_amount, 'f6el': tested_reduction_amount, 'f6em': tested_reduction_amount, 'f6gp': tested_reduction_amount, 'f6gu': tested_reduction_amount}),
    'credit_garext': define_family_scenario(2017, value_by_variable = {'f7ga': 3000, 'f7ge': 2000}, nb_enfants = 2, nbF = 1, nbH = 1),
    'credit_inthab': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7vt': tested_reduction_amount, 'f7vx': tested_reduction_amount * 2, 'f7vz': tested_reduction_amount * 3}),
    'credit_preetu': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7uk': 1000, 'f7vo': 2, 'f7td': 3000}, date_naissance = 2017 - 25),
    'credit_saldom': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7db': tested_income_amount, 'f7dq': 1, 'f7dg': 1}),
    'decote': define_family_scenario(2017, income_amount1 = 25000, income_amount2 = 20000),
    'f4be': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f4be': 15000}), # régime micro-foncier
    'maj_nbp': define_family_scenario(2017, nbF = 1, nbG = 1, nbH = 1, nbI = 1, nbR = 1, nbJ = 1),
    'nbG': define_family_scenario(2017, nbG = 1),  
    'nbI': define_family_scenario(2017, nbF = 2, nbI = 1, nbH = 1),
    'nbR': define_family_scenario(2017, nbR = 1),
    'plaf_qf_caseL': define_single_worker_scenario(2017, {'salaire_imposable': 150000}, caseL = 1),
    'plaf_qf_casePF_nbGI': define_family_scenario(2017, income_amount1 = 150000, income_amount2 = 100000, caseP = 1, caseF = 1, nbF = 2, nbG = 1, nbH = 1, nbI = 1),
    'plaf_qf_caseT': define_single_worker_scenario(2017,  {'salaire_imposable': 150000}, nb_enfants = 1, nbF = 1, caseT = 1),
    'plaf_qf_caseWG': define_single_worker_scenario(2017, {'salaire_imposable': 150000}, statut_marital = u'veuf', caseG = 1, caseW = 1),
    'plaf_qf_family': define_family_scenario(2017, income_amount1 = 150000, income_amount2 = 100000),
    'ppe': define_family_scenario(2017, income_amount1 = 15000, income_amount2 = 10000), 
    'reduc_adhcga': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7ff': tested_reduction_amount, 'f7fg': 2}),
    'reduc_autent': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'f7uy': tested_reduction_amount}),
    'reduc_credit_2042pro': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'abic_impn': fixed_wage_amount, 'arag_impg': fixed_wage_amount, 'f8tb': tested_reduction_amount, 'f8tc' : tested_reduction_amount, 'f8te' : tested_reduction_amount, 'f8tg' : tested_reduction_amount, 'f8ts' : tested_reduction_amount, 'f8tz' : tested_reduction_amount, 'f8wa' : tested_reduction_amount, 'f8wb' : tested_reduction_amount, 'f8wc' : tested_reduction_amount, 'f8wd' : tested_reduction_amount, 'f8we' : tested_reduction_amount, 'f8wt' : tested_reduction_amount, 'f8wr' : tested_reduction_amount, 'f8uz' : tested_reduction_amount, 'f8wu' : tested_reduction_amount, 'f8tl' : tested_reduction_amount, 'f8uw' : tested_reduction_amount}), 
    'reduc_duflot_rpinel': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7el': 200000, 'f7qc': 150000, 'f7qe': tested_reduction_amount, 'f7qh': tested_reduction_amount, 'f7qj': tested_reduction_amount, 'f7ql': tested_reduction_amount, 'f7ai': tested_reduction_amount, 'f7gh': tested_reduction_amount, 'f7fi': tested_reduction_amount}),
    'reduc_dfppce' : define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7uf': tested_reduction_amount, 'f7vc': tested_reduction_amount, 'f7xs': 1000, 'f7xt': 1000, 'f7xu': 1000, 'f7xv': 1000, 'f7xw': 1000}),
    'reduc_donapd' : define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7ud': 100, 'f7va': 100}),
    'reduc_ecpess': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount,'f7ea': 1, 'f7eb': 1, 'f7ec': 0, 'f7ef': 0, 'f7eg': 0, 'f7ed': 1}, nb_enfants = 3, nbF = 1, nbH = 2),
    'reduc_intagr': define_single_worker_scenario(2017,  {'salaire_imposable': fixed_wage_amount, 'f7um': tested_income_amount, 'f2tr': tested_income_amount}),
    'reduc_invlst1': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7uy': 5000}),
    'reduc_invlst2': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7uz': 5000}),
    'reduc_patnat': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7kb': tested_reduction_amount, 'f7kc': tested_reduction_amount, 'f7kd': tested_reduction_amount, 'f7ke': tested_reduction_amount}),
    'reduc_malraux': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7ny': tested_reduction_amount, 'f7nx': tested_reduction_amount, 'f7re': tested_reduction_amount, 'f7rf': tested_reduction_amount, 'f7sy': tested_reduction_amount, 'f7sx': tested_reduction_amount}),
    'reduc_saldom' : define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7df': tested_income_amount, 'f7dq': 0, 'f7dg': 0}),
    'reduc_saldom2': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7dd': tested_income_amount, 'f7dl': 1}),
    'reduc_spfscpi': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount, 'f7fq': tested_reduction_amount * 2, 'f7fm': tested_reduction_amount * 3}),
    'reduc_spfscpi2': define_single_worker_scenario(2017, {'salaire_imposable': fixed_wage_amount, 'f7gq': tested_reduction_amount}),
}

scenario_by_variable = {
    '2014' : scenario_by_variable_2014,
    '2015' : scenario_by_variable_2015,
    '2016' : scenario_by_variable_2016,
    '2017' : scenario_by_variable_2017,
}