###############################################################################
## File for Anaconda.org
## It use Jinja2 templating code to retreive information from setup.py
###############################################################################

{% set name = "OpenFisca-France" %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - numpy >=1.24.2,<2.0
    - pip
  run:
    {% for req in data.get('install_requires', []) %}
    - {{ req }}
    {% endfor %}


test:
  imports:
    - openfisca_france
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: openfisca-france

  - name: openfisca-france-scipy
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - scipy >=1.10.1,<2.0
        - {{ pin_subpackage('openfisca-france', exact=True) }}

  - name: openfisca-france-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.9,<4.0
        {% for req in data.get('dev_requirements', []) %}
        - {{ req }}
        {% endfor %}
        - {{ pin_subpackage('openfisca-france-scipy', exact=True) }}

about:
  home: https://fr.openfisca.org/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE.AGPL.txt
  summary: "French tax and benefit system for OpenFisca"
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the OpenFisca model of the French tax and benefit system.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/openfisca-france/
