###############################################################################
## File for Anaconda.org
## It uses Jinja2 templating code to retrieve information from pyproject.toml
###############################################################################

{% set name = "OpenFisca-France" %}
{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    {% for req in pyproject.get('project').get('dependencies') %}
    - {{ req }}
    {% endfor %}
    # - python >=3.9,<4.0
    # - OpenFisca-Core >=40,<41


test:
  imports:
    - openfisca_france
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: openfisca-france

  - name: openfisca-france-scipy
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - scipy >=1.10.1,<2.0
        - {{ pin_subpackage('openfisca-france', exact=True) }}

  - name: openfisca-france-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.9,<4.0
        # {% for req in pyproject.get('project').get('optional-dependencies').get('dev') %}
        # - {{ req }}
        # {% endfor %}
        - autopep8 >=2.0.2, <3.0
        - flake8 >=6.0.0, <7.0.0
        - flake8-print >=5.0.0, <6.0
        - flake8-quotes >=3.3.2
        - pytest >=7.2.2, <8.0
        - scipy >=1.10.1, <2.0
        - requests >=2.28.2, <3.0
        - yamllint >=1.30.0, <2.0
        - {{ pin_subpackage('openfisca-france-scipy', exact=True) }}

about:
  home: https://fr.openfisca.org/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE.AGPL.txt
  summary: "French tax and benefit system for OpenFisca"
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the OpenFisca model of the French tax and benefit system.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/openfisca-france/
