description: Prélèvements libératoires sur les revenus des valeurs mobilières, Produits de placements à revenu fixe (n'excédant pas 2000 €) (1965-2017)
values:
  2012-01-01:
    value: null
  2013-01-01:
    value: 0.24
metadata:
  short_label: Produits de placements à revenu fixe (n'excédant pas 2000€)
  label_en: Levy in discharge on capital income (1965 - 2012)
  unit: /1
  reference:
    2010-03-01:
      title: Loi 2009-1674 du 30/12/2009, art. 22
      href: https://www.legifrance.gouv.fr/eli/loi/2009/12/30/2009-1674/jo/article_22
    2012-01-01:
      title: Loi 2011-1978 du 28/12/2011, art. 20 et 59 (LFR pour 2011)
    2013-01-01:
      title: Loi 2012-1509 du 29/12/2012, art. 9(LFR pour 2013)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000026872653&cidTexte=JORFTEXT000026856853
  official_journal_date:
    2010-03-01: "2009-12-31"
    2012-01-01: "2011-12-29"
    2013-01-01: "2012-12-30"
  notes:
    2012-01-01:
    - title: La modification du taux appliqué aux revenus du PEP reste théorique puisque tous les PEP ont plus de huit ans.
    2013-01-01:
    - title: Le prélèvement forfaitaire libératoire est supprimé (à l'exception du cas des produits de placement à revenu fixe n'excédant pas 2000 €) par la loi de finances pour 2013. Un prélèvement forfaitaire obligatoire et non libératoire le remplace. Voir note (2)
documentation: |-
  Notes :
  Etat "non-coopératif" : défini à l'article 238-0 A du CGI
  Références du Code général des impôts : l'article 125 A du CGI régit le prélèvement sur les produits de placements à revenu fixe tandis que l'article 117 quater régit le prélèvement sur les dividendes.
