description: Prélèvements sociaux sur les produits de placement
values:
  1998-01-01:
    value: 0.02
  2011-01-01:
    value: 0.022
  2011-10-01:
    value: 0.034
  2012-07-01:
    value: 0.054
  2013-01-01:
    value: 0.045
  2019-01-01:
    value: null
metadata:
  short_label: Produits de placement
  label_en: Other social levies on financial income
  ipp_csv_id: tx_ps_plac
  unit: /1
  reference:
    1998-01-01:
      title: Loi 97-1164 du 19/12/1997, art. 9 (LFSS pour 1998)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006757363&cidTexte=JORFTEXT000000569121
    2011-01-01:
      title: Loi 2010-1657 du 29/12/2010, art. 6
      href: https://www.legifrance.gouv.fr/eli/loi/2010/12/29/2010-1657/jo/article_6
    2011-10-01:
      title: Loi 2011-1117 du 19/09/2011, art. 10 (LFR pour 2011)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000024576244&cidTexte=JORFTEXT000024574328
    2012-07-01:
      title: Loi 2012-354 du 14/03/2012, art. 2
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000025511608&cidTexte=JORFTEXT000025509584
    2013-01-01:
      title: Loi 2012-1404 du 17/12/2012, art. 3
      href: https://www.legifrance.gouv.fr/eli/loi/2012/12/17/2012-1404/jo/article_3
    2019-01-01:
      title: Loi 2018-1203 du 22/12/2018 - art. 26
      href: https://www.legifrance.gouv.fr/eli/loi/2018/12/22/CPAX1824950L/jo/texte
  official_journal_date:
    1998-01-01: "1997-12-23"
    2011-01-01: "2010-12-30"
    2011-10-01: "2011-09-20"
    2012-07-01: "2012-03-15"
    2013-01-01: "2012-12-18"
    2019-01-01: "2018-12-23"
  notes:
    1998-01-01:
    - title: Les prélèvements sociaux de 2% instaurés en 1997 remplacent le prélèvement social exceptionnel affecté à la CNAF et la contribution sociale permanente affectée à la CNAV.
    2019-01-01:
    - title: Création d'un prélèvement de solidarité directement affecté au budget de l'Etat. Il s'applique aux revenus de placement réalisés à partir de 2019. Cf. XIV art. 26 loi 2018-1203
documentation: |-
  Notes : (1) La loi 2012-354 du 14/03/2012 qui augmentait le taux du PS sur les revenus du patrimoine à 5,4% ne semble pas s'appliquer à cause de la rétroactivité de la loi 2012-1404 du 17/12/2012 et de l'annualisation de l'imposition des revenus du patrimoine.
  Références dans les codes législatifs :
  - Les prélèvements sociaux sur les revenus du patrimoine et sur les produits de placement, ainsi que les taux de ces prélèvements sont codifiés respectivement aux articles L245-14, L245-15 et L245-16 du Code de la sécurité sociale (repris à l'article 1600-0 F du CGI).
  - Les contributions additionnelles au prélèvement social (CAPS) sur les revenus du patrimoine et sur les produits de placement sont codifées à l'article L14-10-4 du Code de l'action sociale et des familles.
  - La contribution RSA est référencée à l'article L262-24 du Code de l'action sociale et des familles.
  - Les prélèvements de solidarité sur les revenus du patrimoine et sur les produits de placement sont codifiés à l'article 1600-0 S du CGI.
