description: Prélèvements de solidarité sur les produits de placement
values:
  2013-01-01:
    value: 0.02
  2019-01-01:
    value: 0.075
metadata:
  short_label: Produits de placement
  label_en: Other social levies on financial income
  ipp_csv_id: tx_pds_plac
  unit: /1
  reference:
    2013-01-01:
      title: Loi 2012-1404 du 17/12/2012, art. 3
      href: https://www.legifrance.gouv.fr/eli/loi/2012/12/17/2012-1404/jo/article_3
    2019-01-01:
      title: Loi 2018-1203 du 22/12/2018 - art. 26
      href: https://www.legifrance.gouv.fr/eli/loi/2018/12/22/CPAX1824950L/jo/texte
  official_journal_date:
    2013-01-01: "2012-12-18"
    2019-01-01: "2018-12-23"
  notes:
    2019-01-01:
    - title: Création d'un prélèvement de solidarité directement affecté au budget de l'Etat. Il s'applique aux revenus de placement réalisés à partir de 2019. Cf. XIV art. 26 loi 2018-1203
