description: Taux sur les produits de placement de la contribution au remboursement de la dette sociale (CRDS) sur les revenus du capital
values:
  1996-02-01:
    value: 0.005
metadata:
  short_label: Produits de placement
  last_value_still_valid_on: "1996-01-01"
  label_en: CRDS on financial income
  ipp_csv_id: tx_crds_rk_plac
  unit: /1
  reference:
    1996-02-01:
      title: Ordonnance 96-50 du 24/01/1996, art. 15, 16 et 19
