description: Taux de la Contribution au Remboursement de la Dette Sociale (CRDS) sur les revenus du capital (produits de placement)
unit: /1
values:
  1990-01-01:
    value: null
  1996-02-01:
    value: 0.005
metadata:
  ux_name: Taux CRDS capital produits de placement
  last_review:
    1996-01-01
  reference:
    1996-02-01: Ordonnance 96-50 du 24/01/1996, art. 15, 16 et 19
    1996-01-01:
    - title: Loi 96-1160 du 27/12/1996, art. 17 (LFSS pour 1997)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006757295&cidTexte=JORFTEXT000000198309
    - title: Loi 96-1181 du 30/12/1996, art. 94 (LF pour 1997)
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006319749&cidTexte=JORFTEXT000000380034
  official_journal_date:
    1996-01-01: 1996-12-29; 1996-12-31
  notes:
  description_en: CRDS on financial income
documentation: |
  Référence dans les codes législatifs :
  Pour le taux de CRDS : l'ordonnance 96-50 du 24/01/1996 est codifiée aux articles 1600-0 G à 1600-0 J du CGI.
